// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPPuYMQVMosZ2ziRUyE0BKEBJlMMc6Hkg',
    appId: '1:159683839798:web:1d6c5a09458158d3825597',
    messagingSenderId: '159683839798',
    projectId: 'fir-6b582',
    authDomain: 'fir-6b582.firebaseapp.com',
    storageBucket: 'fir-6b582.firebasestorage.app',
    measurementId: 'G-EXBPWW2ZRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwQPFaHTdR-7O2MvBHSt6f9Oc28dGsYU',
    appId: '1:159683839798:android:684b35c043ced674825597',
    messagingSenderId: '159683839798',
    projectId: 'fir-6b582',
    storageBucket: 'fir-6b582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHL_LZXW5SfWPnmdWkfyWWdMaJniIZIM',
    appId: '1:159683839798:ios:9e36b2418eec39a7825597',
    messagingSenderId: '159683839798',
    projectId: 'fir-6b582',
    storageBucket: 'fir-6b582.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHL_LZXW5SfWPnmdWkfyWWdMaJniIZIM',
    appId: '1:159683839798:ios:9e36b2418eec39a7825597',
    messagingSenderId: '159683839798',
    projectId: 'fir-6b582',
    storageBucket: 'fir-6b582.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPPuYMQVMosZ2ziRUyE0BKEBJlMMc6Hkg',
    appId: '1:159683839798:web:452fb4a63608d46c825597',
    messagingSenderId: '159683839798',
    projectId: 'fir-6b582',
    authDomain: 'fir-6b582.firebaseapp.com',
    storageBucket: 'fir-6b582.firebasestorage.app',
    measurementId: 'G-JXKCNF8PN1',
  );
}
